BEGIN;

-- =========================================================
-- 1) FUNCTION cập nhật updated_at tự động
-- =========================================================
CREATE OR REPLACE FUNCTION set_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- =========================================================
-- 2) MASTER TABLES
-- =========================================================

CREATE TABLE IF NOT EXISTS "ORGANIZATIONS" (
  organization_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_code VARCHAR(50) NOT NULL,
  organization_name VARCHAR(255) NOT NULL,
  organization_type VARCHAR(30) NOT NULL,
  business_registration_no VARCHAR(100),
  tax_code VARCHAR(100),
  headquarters_address TEXT,
  phone_number VARCHAR(30),
  email VARCHAR(255),
  legal_representative VARCHAR(255),
  operating_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_organizations_code UNIQUE (organization_code),
  CONSTRAINT uq_organizations_business_registration_no UNIQUE (business_registration_no),
  CONSTRAINT uq_organizations_tax_code UNIQUE (tax_code),
  CONSTRAINT uq_organizations_email UNIQUE (email),

  CONSTRAINT chk_organizations_type
    CHECK (organization_type IN ('ENTERPRISE', 'REGULATORY_AGENCY')),

  CONSTRAINT chk_organizations_operating_status
    CHECK (operating_status IN ('ACTIVE', 'SUSPENDED', 'INACTIVE'))
);

CREATE TABLE IF NOT EXISTS "WALLETS" (
  wallet_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  wallet_address VARCHAR(255) NOT NULL,
  blockchain_network VARCHAR(100) NOT NULL,
  public_key TEXT,
  wallet_status VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_wallets_organization
    FOREIGN KEY (organization_id)
    REFERENCES "ORGANIZATIONS" (organization_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_wallets_wallet_address UNIQUE (wallet_address),
  CONSTRAINT uq_wallets_public_key UNIQUE (public_key),

  CONSTRAINT chk_wallets_status
    CHECK (wallet_status IN ('ACTIVE', 'INACTIVE', 'SUSPENDED'))
);

CREATE TABLE IF NOT EXISTS "ACCOUNTS" (
  account_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL,
  account_status VARCHAR(30) NOT NULL DEFAULT 'ACTIVE',
  account_role VARCHAR(30) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_accounts_wallet
    FOREIGN KEY (wallet_id)
    REFERENCES "WALLETS" (wallet_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_accounts_wallet UNIQUE (wallet_id),

  CONSTRAINT chk_accounts_status
    CHECK (account_status IN ('ACTIVE', 'SUSPENDED', 'PERMANENTLY_LOCKED')),

  CONSTRAINT chk_accounts_role
    CHECK (account_role IN ('ORGANIZATION', 'ADMIN'))
);

CREATE TABLE IF NOT EXISTS "PROJECTS" (
  project_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_code VARCHAR(100) NOT NULL,
  project_name VARCHAR(255) NOT NULL,
  project_description TEXT,
  sector VARCHAR(255) NOT NULL,
  country VARCHAR(100) NOT NULL,
  province_city VARCHAR(100),
  ward_commune VARCHAR(100),
  owner_organization_id BIGINT NOT NULL,
  start_date DATE,
  end_date DATE,
  registration_approved_at DATE,
  remaining_emission_reduction NUMERIC(20,4) NOT NULL DEFAULT 0,
  remaining_carbon_credit NUMERIC(20,4) NOT NULL DEFAULT 0,
  project_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_MINT',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_projects_owner_organization
    FOREIGN KEY (owner_organization_id)
    REFERENCES "ORGANIZATIONS" (organization_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_projects_code UNIQUE (project_code),

  CONSTRAINT chk_projects_remaining_emission_reduction
    CHECK (remaining_emission_reduction >= 0),

  CONSTRAINT chk_projects_remaining_carbon_credit
    CHECK (remaining_carbon_credit >= 0),

  CONSTRAINT chk_projects_status
    CHECK (project_status IN ('PENDING_MINT', 'MINTED', 'MINT_CANCELLED')),

  CONSTRAINT chk_projects_date_range
    CHECK (end_date IS NULL OR start_date IS NULL OR end_date >= start_date)
);

CREATE TABLE IF NOT EXISTS "CREDITS" (
  credit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  credit_code VARCHAR(100) NOT NULL,
  project_id BIGINT NOT NULL,
  amount NUMERIC(20,4) NOT NULL,
  issuance_year INT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_credits_project
    FOREIGN KEY (project_id)
    REFERENCES "PROJECTS" (project_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_credits_code UNIQUE (credit_code),
  CONSTRAINT uq_credits_project_year UNIQUE (project_id, issuance_year),

  CONSTRAINT chk_credits_amount
    CHECK (amount > 0),

  CONSTRAINT chk_credits_issuance_year
    CHECK (issuance_year BETWEEN 1900 AND 2100)
);

CREATE TABLE IF NOT EXISTS "TOKEN_BATCHES" (
  batch_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  token_id_on_chain VARCHAR(255),
  mint_tx_hash VARCHAR(255),
  batch_status VARCHAR(30) NOT NULL DEFAULT 'PENDING_MINT',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_token_batches_token_id_on_chain UNIQUE (token_id_on_chain),
  CONSTRAINT uq_token_batches_mint_tx_hash UNIQUE (mint_tx_hash),

  CONSTRAINT chk_token_batches_status
    CHECK (batch_status IN ('PENDING_MINT', 'MINTED', 'FAILED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS "BATCH_DETAIL" (
  batch_credit_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_id BIGINT NOT NULL,
  credit_id BIGINT NOT NULL,
  minted_amount NUMERIC(20,4) NOT NULL,

  CONSTRAINT fk_batch_detail_batch
    FOREIGN KEY (batch_id)
    REFERENCES "TOKEN_BATCHES" (batch_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_batch_detail_credit
    FOREIGN KEY (credit_id)
    REFERENCES "CREDITS" (credit_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_batch_detail_batch_credit UNIQUE (batch_id, credit_id),

  CONSTRAINT chk_batch_detail_minted_amount
    CHECK (minted_amount > 0)
);

-- =========================================================
-- 3) MARKET / GIAO DỊCH
-- =========================================================

CREATE TABLE IF NOT EXISTS "LISTINGS" (
  listing_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  batch_credit_id BIGINT NOT NULL,
  listing_price NUMERIC(20,2) NOT NULL,
  seller_wallet_id BIGINT NOT NULL,
  listed_amount NUMERIC(20,4) NOT NULL,
  listing_status VARCHAR(20) NOT NULL DEFAULT 'OPEN',
  listing_tx_hash VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_listings_batch_credit
    FOREIGN KEY (batch_credit_id)
    REFERENCES "BATCH_DETAIL" (batch_credit_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_listings_seller_wallet
    FOREIGN KEY (seller_wallet_id)
    REFERENCES "WALLETS" (wallet_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_listings_tx_hash UNIQUE (listing_tx_hash),

  CONSTRAINT chk_listings_price
    CHECK (listing_price >= 0),

  CONSTRAINT chk_listings_amount
    CHECK (listed_amount > 0),

  CONSTRAINT chk_listings_status
    CHECK (listing_status IN ('OPEN', 'CLOSED', 'CANCELLED'))
);

CREATE TABLE IF NOT EXISTS "CARBON_QUOTAS" (
  quota_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  quota_year INT NOT NULL,
  allocated_quota NUMERIC(20,4) NOT NULL,
  actual_emission NUMERIC(20,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_carbon_quotas_organization
    FOREIGN KEY (organization_id)
    REFERENCES "ORGANIZATIONS" (organization_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_carbon_quotas_org_year UNIQUE (organization_id, quota_year),

  CONSTRAINT chk_carbon_quotas_allocated
    CHECK (allocated_quota >= 0),

  CONSTRAINT chk_carbon_quotas_actual
    CHECK (actual_emission >= 0),

  CONSTRAINT chk_carbon_quotas_year
    CHECK (quota_year BETWEEN 1900 AND 2100)
);

CREATE TABLE IF NOT EXISTS "TOKEN_BALANCES" (
  balance_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL,
  batch_credit_id BIGINT NOT NULL,
  current_amount NUMERIC(20,4) NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_token_balances_wallet
    FOREIGN KEY (wallet_id)
    REFERENCES "WALLETS" (wallet_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_token_balances_batch_credit
    FOREIGN KEY (batch_credit_id)
    REFERENCES "BATCH_DETAIL" (batch_credit_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_token_balances_wallet_batch_credit UNIQUE (wallet_id, batch_credit_id),

  CONSTRAINT chk_token_balances_current_amount
    CHECK (current_amount >= 0)
);

CREATE TABLE IF NOT EXISTS "TRADES" (
  trade_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  listing_id BIGINT NOT NULL,
  trade_amount NUMERIC(20,4) NOT NULL,
  unit_price NUMERIC(20,2) NOT NULL,
  fee_amount NUMERIC(20,2) NOT NULL DEFAULT 0,
  trade_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  buyer_wallet_id BIGINT NOT NULL,
  executed_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  trade_tx_hash VARCHAR(255),

  CONSTRAINT fk_trades_listing
    FOREIGN KEY (listing_id)
    REFERENCES "LISTINGS" (listing_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_trades_buyer_wallet
    FOREIGN KEY (buyer_wallet_id)
    REFERENCES "WALLETS" (wallet_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_trades_tx_hash UNIQUE (trade_tx_hash),

  CONSTRAINT chk_trades_amount
    CHECK (trade_amount > 0),

  CONSTRAINT chk_trades_unit_price
    CHECK (unit_price >= 0),

  CONSTRAINT chk_trades_fee_amount
    CHECK (fee_amount >= 0),

  CONSTRAINT chk_trades_status
    CHECK (trade_status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')),

  CONSTRAINT chk_trades_executed_at
    CHECK (trade_status <> 'COMPLETED' OR executed_at IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS "TOKEN_ACTIVITY_LOGS" (
  activity_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id BIGINT NOT NULL,
  batch_credit_id BIGINT NOT NULL,
  activity_type VARCHAR(20) NOT NULL,
  delta_amount NUMERIC(20,4) NOT NULL,
  balance_after NUMERIC(20,4) NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  reference_id BIGINT NOT NULL,
  reference_type VARCHAR(20) NOT NULL,

  CONSTRAINT fk_token_activity_logs_wallet
    FOREIGN KEY (wallet_id)
    REFERENCES "WALLETS" (wallet_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_token_activity_logs_batch_credit
    FOREIGN KEY (batch_credit_id)
    REFERENCES "BATCH_DETAIL" (batch_credit_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT chk_token_activity_logs_activity_type
    CHECK (activity_type IN ('MINT', 'BUY', 'SELL', 'RETIRE')),

  CONSTRAINT chk_token_activity_logs_delta_amount
    CHECK (delta_amount <> 0),

  CONSTRAINT chk_token_activity_logs_balance_after
    CHECK (balance_after >= 0),

  CONSTRAINT chk_token_activity_logs_reference_type
    CHECK (reference_type IN ('MINT', 'TRADE', 'RETIREMENT', 'LISTING'))
);

CREATE TABLE IF NOT EXISTS "RETIREMENTS" (
  retirement_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  organization_id BIGINT NOT NULL,
  wallet_id BIGINT NOT NULL,
  quota_id BIGINT NOT NULL,
  retirement_status VARCHAR(20) NOT NULL DEFAULT 'PENDING',
  retired_at TIMESTAMPTZ,
  retirement_tx_hash VARCHAR(255),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT fk_retirements_organization
    FOREIGN KEY (organization_id)
    REFERENCES "ORGANIZATIONS" (organization_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_retirements_wallet
    FOREIGN KEY (wallet_id)
    REFERENCES "WALLETS" (wallet_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT fk_retirements_quota
    FOREIGN KEY (quota_id)
    REFERENCES "CARBON_QUOTAS" (quota_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_retirements_tx_hash UNIQUE (retirement_tx_hash),

  CONSTRAINT chk_retirements_status
    CHECK (retirement_status IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')),

  CONSTRAINT chk_retirements_retired_at
    CHECK (retirement_status <> 'COMPLETED' OR retired_at IS NOT NULL)
);

CREATE TABLE IF NOT EXISTS "RETIREMENT_DETAIL" (
  retirement_detail_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  retirement_id BIGINT NOT NULL,
  batch_credit_id BIGINT NOT NULL,
  retired_amount NUMERIC(20,4) NOT NULL,

  CONSTRAINT fk_retirement_detail_retirement
    FOREIGN KEY (retirement_id)
    REFERENCES "RETIREMENTS" (retirement_id)
    ON UPDATE CASCADE
    ON DELETE CASCADE,

  CONSTRAINT fk_retirement_detail_batch_credit
    FOREIGN KEY (batch_credit_id)
    REFERENCES "BATCH_DETAIL" (batch_credit_id)
    ON UPDATE CASCADE
    ON DELETE RESTRICT,

  CONSTRAINT uq_retirement_detail_retirement_batch_credit UNIQUE (retirement_id, batch_credit_id),

  CONSTRAINT chk_retirement_detail_retired_amount
    CHECK (retired_amount > 0)
);

-- =========================================================
-- 4) IPFS
-- =========================================================

CREATE TABLE IF NOT EXISTS "IPFS_FILES" (
  ipfs_file_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  object_type VARCHAR(30) NOT NULL,
  object_id BIGINT NOT NULL,
  file_type VARCHAR(50) NOT NULL,
  cid TEXT NOT NULL,
  file_name VARCHAR(255) NOT NULL,
  mime_type VARCHAR(100),
  file_size BIGINT,
  is_public BOOLEAN NOT NULL DEFAULT TRUE,
  uploaded_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  CONSTRAINT uq_ipfs_files_object_file UNIQUE (object_type, object_id, file_type, cid),

  CONSTRAINT chk_ipfs_files_object_type
    CHECK (object_type IN ('PROJECT', 'CREDIT', 'TOKEN_BATCH', 'RETIREMENT')),

  CONSTRAINT chk_ipfs_files_file_type
    CHECK (file_type IN ('PROJECT_METADATA', 'MRV_REPORT', 'TOKEN_METADATA', 'RETIREMENT_CERTIFICATE')),

  CONSTRAINT chk_ipfs_files_file_size
    CHECK (file_size IS NULL OR file_size >= 0)
);

-- =========================================================
-- 5) INDEXES
-- =========================================================

CREATE INDEX IF NOT EXISTS idx_wallets_organization_id
  ON "WALLETS" (organization_id);

CREATE INDEX IF NOT EXISTS idx_projects_owner_organization_id
  ON "PROJECTS" (owner_organization_id);

CREATE INDEX IF NOT EXISTS idx_credits_project_id
  ON "CREDITS" (project_id);

CREATE INDEX IF NOT EXISTS idx_batch_detail_batch_id
  ON "BATCH_DETAIL" (batch_id);

CREATE INDEX IF NOT EXISTS idx_batch_detail_credit_id
  ON "BATCH_DETAIL" (credit_id);

CREATE INDEX IF NOT EXISTS idx_listings_batch_credit_id
  ON "LISTINGS" (batch_credit_id);

CREATE INDEX IF NOT EXISTS idx_listings_seller_wallet_id
  ON "LISTINGS" (seller_wallet_id);

CREATE INDEX IF NOT EXISTS idx_carbon_quotas_organization_id
  ON "CARBON_QUOTAS" (organization_id);

CREATE INDEX IF NOT EXISTS idx_token_balances_wallet_id
  ON "TOKEN_BALANCES" (wallet_id);

CREATE INDEX IF NOT EXISTS idx_token_balances_batch_credit_id
  ON "TOKEN_BALANCES" (batch_credit_id);

CREATE INDEX IF NOT EXISTS idx_trades_listing_id
  ON "TRADES" (listing_id);

CREATE INDEX IF NOT EXISTS idx_trades_buyer_wallet_id
  ON "TRADES" (buyer_wallet_id);

CREATE INDEX IF NOT EXISTS idx_token_activity_logs_wallet_id
  ON "TOKEN_ACTIVITY_LOGS" (wallet_id);

CREATE INDEX IF NOT EXISTS idx_token_activity_logs_batch_credit_id
  ON "TOKEN_ACTIVITY_LOGS" (batch_credit_id);

CREATE INDEX IF NOT EXISTS idx_retirements_organization_id
  ON "RETIREMENTS" (organization_id);

CREATE INDEX IF NOT EXISTS idx_retirements_wallet_id
  ON "RETIREMENTS" (wallet_id);

CREATE INDEX IF NOT EXISTS idx_retirements_quota_id
  ON "RETIREMENTS" (quota_id);

CREATE INDEX IF NOT EXISTS idx_retirement_detail_retirement_id
  ON "RETIREMENT_DETAIL" (retirement_id);

CREATE INDEX IF NOT EXISTS idx_retirement_detail_batch_credit_id
  ON "RETIREMENT_DETAIL" (batch_credit_id);

CREATE INDEX IF NOT EXISTS idx_ipfs_files_object
  ON "IPFS_FILES" (object_type, object_id);

-- =========================================================
-- 6) TRIGGERS updated_at
-- =========================================================

CREATE TRIGGER trg_organizations_set_updated_at
BEFORE UPDATE ON "ORGANIZATIONS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_wallets_set_updated_at
BEFORE UPDATE ON "WALLETS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_accounts_set_updated_at
BEFORE UPDATE ON "ACCOUNTS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_projects_set_updated_at
BEFORE UPDATE ON "PROJECTS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_credits_set_updated_at
BEFORE UPDATE ON "CREDITS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_token_batches_set_updated_at
BEFORE UPDATE ON "TOKEN_BATCHES"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_listings_set_updated_at
BEFORE UPDATE ON "LISTINGS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_carbon_quotas_set_updated_at
BEFORE UPDATE ON "CARBON_QUOTAS"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

CREATE TRIGGER trg_token_balances_set_updated_at
BEFORE UPDATE ON "TOKEN_BALANCES"
FOR EACH ROW
EXECUTE FUNCTION set_updated_at();

COMMIT;